---
title: "Código de Preparación de Datos"
output: html_document
---
```{r Librerías}
pacman::p_load(dplyr, #Manipulacion de datos
               stargazer, #Tablas
               sjmisc, # Tablas
               summarytools, # Tablas
               kableExtra, #Tablas
               sjPlot, #Tablas y gráficos
               corrplot, # Correlaciones
               sessioninfo, # Información de la sesión de trabajo
               multilevel, #para alpha de cronbach
               scales, #cambios en escalas de medición
               VIM) 
getwd()
```

```{r Cargar Base de datos}
#load("1_input/data/original/ELSOC_W01_V4.00_R.RData") #base de datos ola 1
load("../1_input/data/original/ELSOC_W01_CIT_v3.20_R.RData") #base de datos ola 1 + CIT
```

```{r Selección de variables: selección/filtrado/limpieza}
#selección de variables
elsoc_mod <- dplyr::select(
  elsoc_2016a,SEXO=m0_sexo,EDAD=m0_edad, #características socio-demográficas
  URBE=estrato,COMUNA=comuna.x,DISTRITO=distrito,ZONA=zona,MANZANA=manzana, #identificadores geo-espaciales
  FREC_PELEAS=t09_01,FREC_ROBOS=t09_02,FREC_TRAFICO=t09_03, #experiencias de criminalidad
  PERCEP_SEGURIDAD=t10, #sentimiento de seguridad
  REPUTACION_BARRIAL=t08, #reputación barrial
  COST_BIENES=t04_02,COST_VIV=t04_03,COST_TRANS=t04_04, #economía urbana
  FREC_RUIDOS=t11_01,FREC_MASCOT=t11_02,FREC_AMENAZAS=t11_03,FREC_BASURA=t11_04, #conflicto micro social
  AMISTAD=t03_01,SOCIABILIDAD=t03_02,CORDIALIDAD=t03_03,COLABORACION=t03_04, #sociabilidad
  CONFIANZA_VECINOS=t01, #confianza vecinos 
  LAZOS=t04_05, #lazos sociales
  BARRIO_IDEAL=t02_01,INTEGRADO_BARRIO=t02_02,IDENTIFICADO_BARRIO=t02_03,PERTENENCIA_BARRIO=t02_04, #spb
  SEGURIDAD=t06_01,CONECT=t06_02,AREASVR=t06_03,LIMPIEZA=t06_04,PROX_TRAB=t06_05,PROX_COL=t06_06,PROX_COM=t06_07,PROX_FAM=t06_08, #satisf barrio
  PARTICIPACION=c12_01, #participacion en jjvv
  AREAS_VERDES=acverzon,COLEGIOS=acedzon,SERVICIOS_PUBLICOS=accszon,CALIDAD_AMBIENTAL=ambzon, #accesibilidad
  DENSIDAD_BARRIAL=denszon, #densidad
  SCORE_VIOLENCIA=dviolzon,SCORE_SUSTRACCION=drobozon, #criminalidad urbana
  DIVERSIDAD_CREENCIAS=mixrezon,NVLSOEC_ESCO=nivedzon,EXPO_HETE=sdedzon) #conflicto macro

#filtramos sólo para el conglomerado urbano de Santiago
elsoc_mod <- dplyr::filter(elsoc_mod, URBE < 2)

#convertimos no sabe/no responde a NA
elsoc_mod[elsoc_mod == -888] <- NA
elsoc_mod[elsoc_mod == -999] <- NA

view(dfSummary(elsoc_mod, headings=FALSE))

#eliminar NA (de imputar no es necesaria esta df)
sum(is.na(elsoc_mod))
elsoc_clean <- na.omit(elsoc_mod)
```

```{r Manipulación de variables: recodificación/índices/reescalamiento}
##----índice de "Conflictividad Meso-Social"

#subíndice de "Experiencias de Criminalidad en el Barrio"
EXP_CRIMINALIDAD <-((elsoc_clean$FREC_PELEAS + elsoc_clean$FREC_ROBOS + elsoc_clean$FREC_TRAFICO)/3)
elsoc_clean$EXP_CRIMINALIDAD = EXP_CRIMINALIDAD #añadimos el subíndice a la base de datos

#subíndice de "(in)seguridad en el Barrio" recodificamos para invertir los valores de respuesta de modo que mida inseguridad 
elsoc_clean <- mutate(elsoc_clean,PERCEPCION_INSEGURIDAD = car::recode(elsoc_clean$PERCEP_SEGURIDAD,"1 = 5; 2 = 4; 3 = 3; 4 = 2; 5 = 1"))

##----índice de "Conflictividad Micro-social"
CONFLIC_MICRO <-((elsoc_clean$FREC_RUIDOS + elsoc_clean$FREC_MASCOT + elsoc_clean$FREC_AMENAZAS + elsoc_clean$FREC_BASURA)/4)
elsoc_clean$CONFLIC_MICRO = CONFLIC_MICRO #lo añadimos al dataframe

##----índice de "Calidad de relaciones sociales en el barrio" 
CALIDAD_RSBARRIO <- ((elsoc_clean$AMISTAD + elsoc_clean$SOCIABILIDAD + elsoc_clean$CORDIALIDAD + elsoc_clean$COLABORACION)/4)
elsoc_clean$CALIDAD_RSBARRIO=CALIDAD_RSBARRIO #añadimos una nueva columna "CALIDAD_RSBARRIO" al dataframe

##----construimos un índice de "Sentido de pertenencia"
SENTIDO_PERTENENCIA <- ((elsoc_clean$BARRIO_IDEAL + elsoc_clean$INTEGRADO_BARRIO + elsoc_clean$IDENTIFICADO_BARRIO + elsoc_clean$PERTENENCIA_BARRIO)/4)
elsoc_clean$SENTIDO_PERTENENCIA=SENTIDO_PERTENENCIA #añadimos una nueva columna "SENTIDO_PERTENENCIA" al dataframe

##----índice de satisfacción barrial
SATISF_BARRIAL <- ((elsoc_clean$SEGURIDAD + elsoc_clean$CONECT + elsoc_clean$AREASVR + elsoc_clean$LIMPIEZA + elsoc_clean$PROX_TRAB + elsoc_clean$PROX_COL + elsoc_clean$PROX_COM + elsoc_clean$PROX_FAM)/8)
elsoc_clean$SATISF_BARRIAL=SATISF_BARRIAL

##----índice economía urbana
ECON_URB <- ((elsoc_clean$COST_BIENES + elsoc_clean$COST_VIV + elsoc_clean$COST_TRANS)/3)
elsoc_clean$ECON_URB=ECON_URB

##----Validación de índices
tabla_indice_crim <- dplyr::select(elsoc_clean,FREC_PELEAS,FREC_ROBOS,FREC_TRAFICO)
#cronbach(tabla_indice_crim) #0.76

tabla_indice_micro <- dplyr::select(elsoc_clean,FREC_RUIDOS,FREC_MASCOT,FREC_AMENAZAS,FREC_BASURA)
#cronbach(tabla_indice_micro) #0.67

tabla_indice_crrss <- dplyr::select(elsoc_clean,AMISTAD,SOCIABILIDAD,CORDIALIDAD,COLABORACION)
#cronbach(tabla_indice_crrss) #0.81

tabla_indice_spb <- dplyr::select(elsoc_clean,BARRIO_IDEAL,INTEGRADO_BARRIO,IDENTIFICADO_BARRIO,PERTENENCIA_BARRIO)
#cronbach(tabla_indice_spb) #0.87

tabla_indice_stfb <- dplyr::select(elsoc_clean,SEGURIDAD,CONECT,AREASVR,LIMPIEZA,PROX_TRAB,PROX_COL,PROX_COM,PROX_FAM)
#cronbach(tabla_indice_stfb) #0,78

tabla_indice_ecourb <- dplyr::select(elsoc_clean,COST_BIENES,COST_VIV,COST_TRANS)
#cronbach(tabla_indice_ecourb) #0.62

##----Reescalamiento variable de densidad para dejarla en escala de 0 a 1
elsoc_clean$DENSIDAD.RS <- rescale(elsoc_clean$DENSIDAD_BARRIAL)

##----Reescalamiento de variable nivel socioeconómico medido por escolaridad
elsoc_clean$NVLSOEC.RS <- rescale(elsoc_clean$NVLSOEC_ESCO)

##----Reescalamieno variable exposición a la heterogeneidad en escala 0 a 1
elsoc_clean$EXPO_HETE <- rescale(elsoc_clean$EXPO_HETE)

##----Recode en dummy participación barrial
elsoc_clean$PARTICIPACION <- #car::recode(elsoc_clean$PARTICIPACION,"1=0;2=1;3=2")
elsoc_clean$PARTICIPACION <- as.factor(elsoc_clean$PARTICIPACION)

view(dfSummary(elsoc_clean, headings=FALSE))
```

```{r Generación de base de datos para el análisis}
##----creamos data frame con todos los datos necesarios para análisis multinivel
elsoc_barrio <- dplyr::select(
  elsoc_clean,comuna=COMUNA,zona=ZONA,distrito=DISTRITO,
  sentido_pertenencia=SENTIDO_PERTENENCIA,confianza=CONFIANZA_VECINOS, calidad_rrss=CALIDAD_RSBARRIO, lazos=LAZOS,
  exp_crimen=EXP_CRIMINALIDAD,sentimiento_inseguridad=PERCEPCION_INSEGURIDAD,conflicto_micro=CONFLIC_MICRO,rep_barrial=REPUTACION_BARRIAL,
  satisf_barrial=SATISF_BARRIAL,participacion=PARTICIPACION,econ_urb=ECON_URB,
  servicios_publicos=SERVICIOS_PUBLICOS,densidad=DENSIDAD.RS, puntaje_violencia=SCORE_VIOLENCIA,
  puntaje_sustraccion=SCORE_SUSTRACCION, nvl_socioecon=NVLSOEC.RS, expo_hete=EXPO_HETE)

view(dfSummary(elsoc_barrio, headings=FALSE)) 

#calculamos una nueva variable que será el promedio de la variable "Sentido de Pertenencia" agrupada por zona
elsoc_barrio <- elsoc_barrio %>%
  group_by(zona) %>%
  mutate(sentido_pertenencia_meanbyzona = mean(sentido_pertenencia))

#lo mismo agrupado por comuna
elsoc_barrio <- elsoc_barrio %>%
  group_by(comuna) %>%
  mutate(sentido_pertenencia_meanbycomuna = mean(sentido_pertenencia))

#calculamos una nueva variable que será el promedio de la variable "Reputación Barrial" agrupada por zona
elsoc_barrio <- elsoc_barrio%>%
  group_by(zona) %>%
  mutate(rep_barrial_meanbyzona = mean(rep_barrial))

#renombramos las comunas 
elsoc_barrio$comuna <- as.factor(elsoc_barrio$comuna)
elsoc_barrio$comuna <- factor(elsoc_barrio$comuna,labels = c("Santiago", "Cerrillos", "Cerro Navia", "Conchali", "El Bosque", "Estacion Central", "Huechuraba","Independencia", "La Cisterna", "La Florida", "La Granja", "La Pintana", "La Reina", "Las Condes", "Lo Barnechea", "Lo Espejo", "Lo Prado", "Macul", "Maipu", "Nnunnoa", "Pedro Aguirre Cerda", "Pennialolen", "Providencia", "Pudahuel", "Quilicura", "Quinta Normal", "Recoleta", "Renca", "San Joaquin", "San Miguel", "San Ramon", "Vitacura", "Puente Alto", "San Bernardo", "Padre Hurtado"))

#Promedio por comuna
elsoc_barrio = elsoc_barrio %>%  group_by(comuna) %>% mutate(meanage = mean(sentido_pertenencia))
#Desviación estándarpor comuna
elsoc_barrio = elsoc_barrio %>%  group_by(comuna) %>% mutate(sdage = sd(sentido_pertenencia,))
#Tamaño por comuna
elsoc_barrio = elsoc_barrio %>%  group_by(comuna) %>% mutate(count = length(comuna))

#base con descriptivos por comuna 
comunas <- elsoc_barrio %>% group_by(Comuna=to_label(comuna)) %>% summarise("Promedio Sentido de Pertenencia"=mean(meanage), "SD Sentido de Pertenencia"=mean(sdage), N=mean(count)) #%>% print(n = nrow(.))
comunas <- as.data.frame(comunas)
#View(comunas)

elsoc_barrio[24:26] <- list(NULL) 

#Filtrando las comunas con N bajo
elsoc_barrio <- dplyr::filter(elsoc_barrio, comuna!="Vitacura")

#view(dfSummary(elsoc_barrio, headings=FALSE)) 

sum(is.na(elsoc_barrio))
#elsoc_clean <- na.omit(elsoc_barrio)

getwd()
#guardamos base de datos procesada con el fin de hacerla disponible para el análisis 
save(elsoc_barrio,file = "../1_input/data/procesada/elsoc_barrio.RData")
```
```{r}
sessionInfo()
```

