---
title: "Código preparación 2.0 c/Imputación de NA"
author: "Cristóbal Ortiz"
date: "29-04-2021"
output: html_document
---
```{r Ajustes de Markdown,include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = TRUE)
knitr::opts_knit$set(root.dir = "../")
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '')
```

```{r Librerías}
pacman::p_load(dplyr, #Manipulacion de datos
               stargazer, #Tablas
               sjmisc, # Tablas
               summarytools, # Tablas
               kableExtra, #Tablas
               sjPlot, #Tablas y gráficos
               corrplot, # Correlaciones
               sessioninfo, # Información de la sesión de trabajo
               multilevel, #para alpha de cronbach
               scales, #cambios en escalas de medición
               sjlabelled, #etiquetamiento de variables
               mice) #imputar NA 
getwd()
```

```{r Cargar Base de datos}
#load("1_input/data/original/ELSOC_W01_V4.00_R.RData") #base de datos ola 1
load("../1_input/data/original/ELSOC_W01_CIT_v3.20_R.RData") #base de datos ola 1 + CIT
```

```{r Selección de variables: selección/filtrado/limpieza}
#selección de variables
elsoc <- dplyr::select(elsoc_2016a,
  sexo=m0_sexo,edad=m0_edad,educacion=m01,estatus=d01_01, #control 
  urbe=estrato,comuna=comuna.x,distrito,zona,manzana, #identificadores geográficos
  barrio_ideal=t02_01,integrado_barrio=t02_02,identificado_barrio=t02_03,pertenencia_barrio=t02_04, #spb
  amistad=t03_01,sociable=t03_02,cordialidad=t03_03,colaboracion=t03_04, #calidad rrss
  conf_vecinos=t01,lazos=t04_05, prox_fam=t06_08, #capital social
  sent_seguridad=t10,satisf_seguridad=t06_01, # experiencia de inseguridad 
  frec_ruidos=t11_01,frec_mascot=t11_02,frec_amenazas=t11_03,frec_basura=t11_04, #conflictividad vecinal
  conect=t06_02,prox_trabajo=t06_05,prox_col=t06_06,prox_com=t06_07, #satisfacción c/ accesibilidad
  areasvr=t06_03,limpieza=t06_04,estetica=t04_01, #varias sin agrupar
  costo_bienes=t04_02,costo_viv=t04_03,costo_trans=t04_04, #economía urbana
  rep_barrial=t08, #reputación barrial
  res_desagradables=t04_06,act_desagradables=t04_07, #deseabilidad de estilos de vida
  nvl_esco=nivedzon,expo_hete=sdedzon,violencia=dviolzon,sustraccion=drobozon, #entorno social zona
  densidad=denszon,colegios=acedzon,servicios_publicos=accszon,areas_verdes=acverzon, #entorno espacial zona
  nvl_esco_dto=niveddto,expo_hete_dto=sdeddto,violencia_dto=dvioldto,sustraccion_dto=drobodto, #entorno social distrito
  densidad_dto=densdto,colegios_dto=aceddto,servicios_publicos_dto=accsdto,areas_verdes_dto=acverdto) #entorno espacial distrito


#filtramos sólo para el conglomerado urbano de Santiago
elsoc <- dplyr::filter(elsoc, urbe == 1)

#convertimos no sabe/no responde a NA
elsoc[elsoc == -888] <- NA
elsoc[elsoc == -999] <- NA

#view(dfSummary(elsoc, headings = FALSE))

#eliminar NA (de imputar no es necesaria esta df)
sum(is.na(elsoc))
#elsoc <- na.omit(elsoc)
```

```{r Imputación de NA con regresión estocástica}
columns <- names(elsoc)

elsoc_imputed <- mice(elsoc[,names(elsoc) %in% columns],m = 20,
  maxit = 1, method = "norm.nob",seed = 2018,print=F)

elsoc_mod <- mice::complete(elsoc_imputed)

sum(is.na(elsoc_mod))

#elsoc_mod <- na.omit(elsoc_mod)

```

```{r Manipulación de variable Y}

#----Construcción Y: Sentido de pertenencia al barrio
##----índice de "Sentido de pertenencia al barrio"
elsoc_mod$spb_index <- ((elsoc_mod$barrio_ideal + elsoc_mod$integrado_barrio + elsoc_mod$identificado_barrio + elsoc_mod$pertenencia_barrio)/4)

elsoc_mod$spb_index <- set_label(x = elsoc_mod$spb_index, label = "Indice de Sentido de pertenencia al barrio")

##----Niveles de Sentido de Pertenencia al barrio
elsoc_mod$spb_rec <- factor(with(elsoc_mod, case_when(spb_index < 2 ~ 1,
                                                                  spb_index < 3 ~ 2,
                                                                  spb_index < 4 ~ 3,
                                                                  spb_index <= 5 ~ 4)),
                                  labels = c('Muy Bajo','Bajo','Medio', 'Alto'))
attr(elsoc_mod$spb_rec, which = 'label') <- 'Nivel de Sentido de Pertenencia al Barrio'

#sjmisc::frq(elsoc_mod$spb_index)
sjmisc::frq(elsoc_mod$spb_rec)
```

```{r Manipulación de variable X}
#-----Construcción X1: Experiencia de Habitar el Territorio

##----índice de "Percepción de calidad en relaciones sociales barriales" 
elsoc_mod$sociabilidad <- ((elsoc_mod$amistad + elsoc_mod$sociable + elsoc_mod$cordialidad + elsoc_mod$colaboracion)/4)
elsoc_mod$sociabilidad <- set_label(x = elsoc_mod$sociabilidad,label = "Socibilidad Barrial")

##----subíndice de "Percepción de inseguridad en el Barrio" recodificamos para invertir los valores de respuesta de modo que mida inseguridad 
elsoc_mod <- mutate(elsoc_mod,sent_inseguridad = car::recode(elsoc_mod$sent_seguridad,"1 = 5; 2 = 4; 3 = 3; 4 = 2; 5 = 1"))
elsoc_mod <- mutate(elsoc_mod,insatisf_seguridad = car::recode(elsoc_mod$satisf_seguridad, "1 = 5; 2 = 4; 3 = 3; 4 = 2; 5 = 1"))
elsoc_mod$percep_inseguridad <- ((elsoc_mod$sent_inseguridad + elsoc_mod$insatisf_seguridad)/2)

##----índice de "Experiencia de molestias en el barrio"
elsoc_mod$molestias_barrio <- ((elsoc_mod$frec_ruidos + elsoc_mod$frec_mascot + elsoc_mod$frec_amenazas + elsoc_mod$frec_basura)/4)
elsoc_mod$molestias_barrio <- set_label(x = elsoc_mod$molestias_barrio,label = "Experiencia de molestias en el barrio")

##----índice de "Satisfacción con la geografía de oportunidades del barrio"
elsoc_mod$satisf_gobarrio <- ((elsoc_mod$conect + elsoc_mod$prox_trabajo + elsoc_mod$prox_col + elsoc_mod$prox_com)/4)
elsoc_mod$satisf_gobarrio <- set_label(x = elsoc_mod$satisf_gobarrio, label = "Satisfacción con la geografía de oportunidades del barrio")

##----índice de "Experiencia de economía urbana gentrificada"
elsoc_mod$exp_gentrificacion <- ((elsoc_mod$costo_bienes + elsoc_mod$costo_viv + elsoc_mod$costo_trans)/3)
elsoc_mod$exp_gentrificacion <- set_label(x = elsoc_mod$exp_gentrificacion, label = "Experiencia de economía urbana gentrificada en el barrio")

##----índice de "Presencia de estilos de vida deseables"
elsoc_mod$est_vida <- ((elsoc_mod$act_desagradables + elsoc_mod$res_desagradables)/2)
```

```{r Reputación barrial}
##----recodificación de "Reputación barrial"
sjmisc::frq(elsoc_mod$rep_barrial)
elsoc_mod$rep_barrial[elsoc_mod$rep_barrial == "2.992637548829"] <- 2.00
elsoc_mod$rep_barrial[elsoc_mod$rep_barrial == "3.27243296294069"] <- 3.00
elsoc_mod$rep_barrial[elsoc_mod$rep_barrial == "3.9050094591771"] <- 4.00
elsoc_mod$rep_barrial[elsoc_mod$rep_barrial == "4.11437735905476"] <- 4.00

elsoc_mod$repb <- factor(car::recode(elsoc_mod$rep_barrial, "1:2=1;3=2;4:5=3"),
                            labels = c("Estigmatizado","Ni Estigmatizado Ni Prestigioso", "Prestigioso"))
attr(elsoc_mod$repb, which = 'label') <- 'Reputación Barrial'
sjmisc::frq(elsoc_mod$repb)

#calculamos una nueva variable que será el promedio de la variable "Reputación Barrial" agrupada por zona
elsoc_mod <- elsoc_mod %>%
  dplyr::group_by(zona) %>%
  mutate(repb_zona = mean(rep_barrial))

#calculamos una nueva variable que será el promedio de la variable "Reputación Barrial" agrupada por distrito
elsoc_mod <- elsoc_mod %>%
  dplyr::group_by(distrito) %>%
  mutate(repb_dto = mean(rep_barrial))
```

```{r Manipulación de variable Z por zona}
#----Construcción Z1: Entorno Territorial ZONA

##----Reescalamiento variable de densidad para dejarla en escala de 0 a 1
elsoc_mod$densidad <- rescale(elsoc_mod$densidad)
elsoc_mod$densidad <- set_label(x = elsoc_mod$densidad, label = "Densidad Zona")

##----Reescalamiento de variable nivel socioeconómico medido por escolaridad
elsoc_mod$nvl_esco <- rescale(elsoc_mod$nvl_esco)
elsoc_mod$nvl_esco <- set_label(x = elsoc_mod$nvl_esco, label = "Escolaridad Zona")

##----Reescalamieno variable exposición a la heterogeneidad en escala 0 a 1
elsoc_mod$expo_hete <- rescale(elsoc_mod$expo_hete)
elsoc_mod$expo_hete <- set_label(x = elsoc_mod$expo_hete, label = "Heterogeneidad Zona")

##----Accesibilidad a servicios públicos en escala 0 a 1
elsoc_mod$servicios_publicos <- rescale(elsoc_mod$servicios_publicos)
elsoc_mod$servicios_publicos <- set_label(x = elsoc_mod$servicios_publicos, label = "Accesibilidad Zona")

##----Puntaje de violencia en escala 0 a 1
elsoc_mod$violencia <- rescale(elsoc_mod$violencia)
elsoc_mod$violencia <- set_label(x = elsoc_mod$violencia, label = "Peligrosidad Zona")

##----Puntaje de reputación en escala 0 a 1
elsoc_mod$repb_zona <- rescale(elsoc_mod$repb_zona)
elsoc_mod$repb_zona <- set_label(x = elsoc_mod$repb_zona, label = "Peligrosidad Territorial Zona")

```

```{r Manipulación de variable Z por Distrito}
#----Construcción Z2: Entorno Territorial DISTRITO
elsoc_mod$densidad_dto <- rescale(elsoc_mod$densidad_dto)
elsoc_mod$densidad_dto <- set_label(x = elsoc_mod$densidad_dto, label = "Densidad Distrito")

##----Reescalamiento de variable nivel socioeconómico medido por escolaridad
elsoc_mod$nvl_esco_dto <- rescale(elsoc_mod$nvl_esco_dto)
elsoc_mod$nvl_esco_dto <- set_label(x = elsoc_mod$nvl_esco_dto, label = "Escolaridad Distrito")

##----Reescalamieno variable exposición a la heterogeneidad en escala 0 a 1
elsoc_mod$expo_hete_dto <- rescale(elsoc_mod$expo_hete_dto)
elsoc_mod$expo_hete_dto <- set_label(x = elsoc_mod$expo_hete_dto, label = "Heterogeneidad Distrito")

##----Accesibilidad a servicios públicos en escala 0 a 1
elsoc_mod$servicios_publicos_dto <- rescale(elsoc_mod$servicios_publicos_dto)
elsoc_mod$servicios_publicos_dto <- set_label(x = elsoc_mod$servicios_publicos_dto, label = "Accesibilidad Distrito")

##----Puntaje de violencia en escala 0 a 1
elsoc_mod$violencia_dto <- rescale(elsoc_mod$violencia_dto)
elsoc_mod$violencia_dto <- set_label(x = elsoc_mod$violencia_dto, label = "Peligrosidad Distrito")

##----Puntaje de reputación en escala 0 a 1
elsoc_mod$repb_dto <- rescale(elsoc_mod$repb_dto)
elsoc_mod$repb_dto <- set_label(x = elsoc_mod$repb_dto, label = "Reputación Distrito")
```

```{r Estandarización de índices nivel 1}

#elsoc_mod$spb_index <- rescale(elsoc_mod$spb_index)
#elsoc_mod$sociabilidad <- rescale(elsoc_mod$sociabilidad)
#elsoc_mod$percep_inseguridad <- rescale(elsoc_mod$percep_inseguridad)
#elsoc_mod$molestias_barrio <- rescale(elsoc_mod$molestias_barrio)
#elsoc_mod$satisf_gobarrio <- rescale(elsoc_mod$satisf_gobarrio)
#elsoc_mod$est_vida <- rescale(elsoc_mod$est_vida)

sjmisc::frq(elsoc_mod$exp_gentrificacion)
elsoc_mod$exp_gentrificacion[elsoc_mod$exp_gentrificacion == "5.11780836768077"] <- 5.00
#elsoc_mod$exp_gentrificacion <- rescale(elsoc_mod$exp_gentrificacion)

sjmisc::frq(elsoc_mod$conf_vecinos)
#elsoc_mod$conf_vecinos[elsoc_mod$conf_vecinos == "5.45237823883507"] <- 5.00
#elsoc_mod$conf_vecinos <- rescale(elsoc_mod$conf_vecinos)


```


```{r Manipulación variables de control}
#Recode estatus social subjetivo

elsoc_mod$estatus[which(elsoc_mod$estatus ==  "2.19403055532349")] <- 2.00

elsoc_mod$estatus<- factor(car::recode(elsoc_mod$estatus, "0:4=1;5:6=2;7:10=3"),
                          labels = c("Bajo","Medio","Alto"))                          
attr(elsoc_mod$estatus, which = 'label') <- 'Estatus Social Subjetivo'
sjmisc::frq(elsoc_mod$estatus)

#Recode educación
elsoc_mod$educacion[which(elsoc_mod$educacion ==  "5.78721904395982")] <- 6

elsoc_mod$educacion <- car::recode(elsoc_mod$educacion,"1:3=1;4:5=2;6:7=3;8:10=4")
elsoc_mod$educacion <- factor(elsoc_mod$educacion,labels = c("Basica","Media","Tecnica","Universitaria"))

elsoc_mod$educacion <- sjlabelled::set_label(elsoc_mod$educacion, label = c("Nivel Educacional"))
elsoc_mod$educacion <- sjlabelled::set_labels(elsoc_mod$educacion, labels = c("Basica", "Media", "Tecnica", "Universitaria"))
sjmisc::frq(elsoc_mod$educacion)

#Recode edad
elsoc_mod$edad <- factor(car::recode(elsoc_mod$edad, "18:29=1;30:49=2;50:64=3;65:150=4"),
                           labels = c('18-29', '30-49', '50-64', '65 o más'))
attr(elsoc_mod$edad, which = 'label') <- 'Tramo de edad'

elsoc_mod$edad <- sjlabelled::set_label(elsoc_mod$edad, label = c("Edad en Tramos"))
elsoc_mod$edad <- sjlabelled::set_labels(elsoc_mod$edad, labels = c("18 a 29", "30 a 49", "50 a 64", " 65 o mas"))
sjmisc::frq(elsoc_mod$edad)
```

```{r Validación de índices}
tabla_indice_spb <- dplyr::select(elsoc_mod,barrio_ideal,integrado_barrio,identificado_barrio,pertenencia_barrio)
#cronbach(tabla_indice_spb) #0.87

tabla_indice_sociabilidad <- dplyr::select(elsoc_mod,amistad,sociable,cordialidad,colaboracion)
#cronbach(tabla_indice_sociabilidad) #0.81

tabla_indice_percep_inseguridad <- dplyr::select(elsoc_mod,sent_inseguridad,insatisf_seguridad)
#cronbach(tabla_indice_percep_inseguridad) #0,67

tabla_indice_molestias <- dplyr::select(elsoc_mod,frec_ruidos,frec_mascot,frec_amenazas,frec_basura)
#cronbach(tabla_indice_molestias) #0.67

tabla_indice_geop <- dplyr::select(elsoc_mod,conect,prox_trabajo,prox_col,prox_com)
#cronbach(tabla_indice_geop) #0,71

tabla_indice_ecourb <- dplyr::select(elsoc_mod,costo_bienes,costo_viv,costo_trans)
#cronbach(tabla_indice_ecourb) #0.61

tabla_indice_estvida <- dplyr::select(elsoc_mod,res_desagradables,act_desagradables)
#cronbach(tabla_indice_estvida) #0.71
```

```{r Generación de base de datos para el análisis}
##----creamos data frame con todos los datos necesarios para análisis multinivel
elsoc_barrio <- dplyr::select(elsoc_mod,
                              sexo,edad,estatus,educacion, #variables sociodemográficas
                              comuna,zona,distrito, #identificadores geográficos
                              spb_index,spb_rec, #sentido de pertenencia
                              sociabilidad,conf_vecinos,lazos,prox_fam,molestias_barrio, #exp habitar social (sociabilidad y k social)
                              percep_inseguridad, #exp habitar social (seguridad)
                              satisf_gobarrio,exp_gentrificacion, #exp habitar espacial (satisf geo op y econ urbana)
                              repb,est_vida, #exp habitar simbólica
                              nvl_esco, expo_hete,violencia, sustraccion, #entorno territorial social
                              servicios_publicos, densidad,
                              repb_zona) #entorno territorial espacial

#view(dfSummary(elsoc_barrio, headings=FALSE)) 

elsoc_barrio$zona <- as.factor(elsoc_barrio$zona)
#calculamos una nueva variable que será el promedio de la variable "Sentido de Pertenencia" agrupada por zona
elsoc_barrio <- elsoc_barrio %>%
  group_by(zona) %>%
  mutate(spb_zona = mean(spb_index))
sjmisc::frq(elsoc_barrio$spb_zona)

#renombramos las comunas 
elsoc_barrio$comuna <- as.factor(elsoc_barrio$comuna)
elsoc_barrio$comuna <- factor(elsoc_barrio$comuna,labels = c("Santiago", "Cerrillos", "Cerro Navia", "Conchali", "El Bosque", "Estacion Central", "Huechuraba","Independencia", "La Cisterna", "La Florida", "La Granja", "La Pintana", "La Reina", "Las Condes", "Lo Barnechea", "Lo Espejo", "Lo Prado", "Macul", "Maipu", "Nnunnoa", "Pedro Aguirre Cerda", "Pennialolen", "Providencia", "Pudahuel", "Quilicura", "Quinta Normal", "Recoleta", "Renca", "San Joaquin", "San Miguel", "San Ramon", "Vitacura", "Puente Alto", "San Bernardo", "Padre Hurtado"))

#Promedio por comuna
elsoc_barrio = elsoc_barrio %>%  group_by(comuna) %>% mutate(spb_media_comunal = mean(spb_index))
#Desviación estándarpor comuna
elsoc_barrio = elsoc_barrio %>%  group_by(comuna) %>% mutate(spb_sd_comunal = sd(spb_index))
#Tamaño por comuna
elsoc_barrio = elsoc_barrio %>%  group_by(comuna) %>% mutate(spb_n_comunal = length(spb_index))

#base con descriptivos por comuna 
comunas <- elsoc_barrio %>% group_by(comuna=to_label(comuna)) %>% summarise("Promedio Sentido de Pertenencia"=mean(spb_media_comunal), "SD Sentido de Pertenencia"=mean(spb_index), N=mean(spb_n_comunal)) #%>% print(n = nrow(.))
#comunas <- as.data.frame(comunas)
#View(comunas)

#elsoc_barrio[25:27] <- list(NULL) 

#Filtrando las comunas con N bajo
elsoc_barrio <- dplyr::filter(elsoc_barrio, comuna!="Vitacura") #vitacura N=1
#elsoc_barrio <- dplyr::filter(elsoc_barrio, comuna!="Vitacura", comuna!="Lo Barnechea") #Lo Barnechea N=4
getwd()
#guardamos base de datos procesada con el fin de hacerla disponible para el análisis 
save(elsoc_barrio,file = "../1_input/data/procesada/elsoc_barrio.RData")
```
```{r Generación de base de datos para el análisis distrito}
##----creamos data frame con todos los datos necesarios para análisis multinivel
elsoc_barrio_dto <- dplyr::select(elsoc_mod,
                              sexo,edad,estatus,educacion, #variables sociodemográficas
                              comuna,zona,distrito, #identificadores geográficos
                              spb_index,spb_rec, #sentido de pertenencia
                              sociabilidad,conf_vecinos,lazos,prox_fam,molestias_barrio, #exp habitar social (sociabilidad y k social)
                              percep_inseguridad, #exp habitar social (seguridad)
                              satisf_gobarrio,exp_gentrificacion, #exp habitar espacial (satisf geo op y econ urbana)
                              repb,est_vida, #exp habitar simbólica
                              nvl_esco_dto, expo_hete_dto,violencia_dto, sustraccion_dto, #entorno territorial social
                              servicios_publicos_dto, densidad_dto,
                              repb_dto) #entorno territorial espacial

#view(dfSummary(elsoc_barrio, headings=FALSE)) 

#calculamos una nueva variable que será el promedio de la variable "Sentido de Pertenencia" agrupada por zona
elsoc_barrio_dto <- elsoc_barrio_dto %>%
  group_by(distrito) %>%
  mutate(spb_dto = mean(spb_index))


#renombramos las comunas 
elsoc_barrio_dto$comuna <- as.factor(elsoc_barrio_dto$comuna)
elsoc_barrio_dto$comuna <- factor(elsoc_barrio_dto$comuna,labels = c("Santiago", "Cerrillos", "Cerro Navia", "Conchali", "El Bosque", "Estacion Central", "Huechuraba","Independencia", "La Cisterna", "La Florida", "La Granja", "La Pintana", "La Reina", "Las Condes", "Lo Barnechea", "Lo Espejo", "Lo Prado", "Macul", "Maipu", "Nnunnoa", "Pedro Aguirre Cerda", "Pennialolen", "Providencia", "Pudahuel", "Quilicura", "Quinta Normal", "Recoleta", "Renca", "San Joaquin", "San Miguel", "San Ramon", "Vitacura", "Puente Alto", "San Bernardo", "Padre Hurtado"))


#Filtrando las comunas con N bajo
elsoc_barrio_dto <- dplyr::filter(elsoc_barrio_dto, comuna!="Vitacura") #vitacura N=1
#elsoc_barrio <- dplyr::filter(elsoc_barrio, comuna!="Vitacura", comuna!="Lo Barnechea") #Lo Barnechea N=4

#guardamos base de datos procesada con el fin de hacerla disponible para el análisis 
save(elsoc_barrio_dto,file = "../1_input/data/procesada/elsoc_barrio_dto.RData")
```

```{r}
sessionInfo()
```

